#!/usr/bin/env bash

set -e

assert_equal () {
  local red='\033[0;31m'
  local green='\033[0;32m'
  local no_color='\033[0m'
  local expected=$1
  local actual=$2
  local message=${@:3}

  if [[ "$expected" = "$actual" ]]
  then
    printf "$green✓$no_color $message\n"
  else
    printf "$red✗$no_color $message\n"
    printf "$red\n"
    echo "∵ actual:"
    echo "$actual"
    echo "not equal to:"
    echo "$expected"
    printf "$no_color"
    exit 1
  fi
}

echo '{"coauthors":' \
  > "$GIT_MOB_COAUTHORS"
echo '{"ab":{"name":"Andrew Bruce","email":"me@andrewbruce.net"}' \
  >> "$GIT_MOB_COAUTHORS"
echo ',"fb":{"name":"Fred Brookes","email":"fred@example.com"}' \
  >> "$GIT_MOB_COAUTHORS"
echo '}}' \
  >> "$GIT_MOB_COAUTHORS"

expected_output="$(cat <<EOF
Co-authored-by: Andrew Bruce <me@andrewbruce.net>
Co-authored-by: Fred Brookes <fred@example.com>
EOF
)"

actual_output="$(git-mob ab fb)"

assert_equal \
  "$expected_output" \
  "$actual_output" \
  Forming a mob prints the new mob

assert_equal \
  "

$expected_output" \
  "$(cat "$GIT_MOB_TEMPLATE")" \
  Forming a mob writes the commit template

assert_equal \
  "$expected_output" \
  "$(git-mob)" \
  Running git-mob without arguments shows the current mob

assert_equal \
  "ab fb" \
  "$(git-mob initials)" \
  Running git-mob initials shows the initials of the mob

actual_output="$(git-solo)"

assert_equal \
  "" \
  "$actual_output" \
  Soloing shows no output

assert_equal \
  "" \
  "$(cat "$GIT_MOB_TEMPLATE")" \
  Soloing wipes the commit template

assert_equal \
  0 \
  "$(du "$GIT_MOB_TEMPLATE" | cut -f1)" \
  Soloing makes commit template zero length
