#!/usr/bin/env bash

set -e

assert_equal () {
  local red='\033[0;31m'
  local green='\033[0;32m'
  local no_color='\033[0m'
  local expected=$1
  local actual=$2
  local message=${@:3}

  if [[ "$expected" = "$actual" ]]
  then
    printf "$green✓$no_color $message\n"
  else
    printf "$red✗$no_color $message\n"
    printf "$red\n"
    echo "∵ actual:"
    echo "$actual"
    echo "not equal to:"
    echo "$expected"
    printf "$no_color"
    exit 1
  fi
}

echo '{"coauthors":' \
  > "$GIT_MOB_COAUTHORS"
echo '{"ab":{"name":"Andrew Bruce","email":"me@andrewbruce.net"}' \
  >> "$GIT_MOB_COAUTHORS"
echo ',"fb":{"name":"Fred Brookes","email":"fred@example.com"}' \
  >> "$GIT_MOB_COAUTHORS"
echo '}}' \
  >> "$GIT_MOB_COAUTHORS"

git-solo

actual_output="$(git-mob-generate-dialog-args "$GIT_MOB_COAUTHORS" "$GIT_MOB_LIST")"

assert_equal "0 0 0 ab 'Andrew Bruce' off fb 'Fred Brookes' off" \
  "$actual_output" \
  With empty mob, dialog command is generated with nothing selected.

git-mob ab > /dev/null
actual_output="$(git-mob-generate-dialog-args "$GIT_MOB_COAUTHORS" "$GIT_MOB_LIST")"

assert_equal "0 0 0 ab 'Andrew Bruce' on fb 'Fred Brookes' off" \
  "$actual_output" \
  With nonempty mob, dialog command is generated with selected mobsters.
