#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

src="$1"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
mob_list_file=${GIT_MOB_LIST=~/.git-mob}
mob_message="$(git-mob-print "$coauthors_file" "$mob_list_file")"

if
  [[ -z "$mob_message"
  || -z "$(git branch --show-current)"
  || -n "$(git interpret-trailers --parse "$src")"
  ]]
then
  exit 0
fi

is_only_comments() {
  [[ "$(tr -d '\n')" == "#"* ]]
}

put_message_above_comments() {
  local reached_comment=false;

  while read -r line
  do
    if [[ "$line" == "#"* && "$reached_comment" == false ]]
    then
      echo "$mob_message"
      echo
      reached_comment=true;
    fi
    echo "$line"
  done

  if [[ "$reached_comment" == false ]]
  then
    echo
    echo "$mob_message"
  fi
}

new_contents="$(
  is_only_comments < "$src" && echo
  put_message_above_comments < "$src"
)"

echo "$new_contents" > "$src"
