#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

src="$1"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
mob_list_file=${GIT_MOB_LIST=~/.git-mob}
mob_message="$(git-mob-print "$coauthors_file" "$mob_list_file")"

if
  [[ -z "$mob_message"
  || -z "$(git branch --show-current)"
  || -n "$(git interpret-trailers --parse "$src")"
  ]]
then
  exit 0
fi

dst="$(mktemp)"

[[ "$(tr -d '\n' < "$src")" == "#"* ]] && echo >> "$dst"

reached_comment=false;
while read -r line
do
  if [[ "$line" == "#"* && "$reached_comment" == false ]]
  then
    echo "$mob_message" >> "$dst"
    echo >> "$dst"
    reached_comment=true;
  fi
  echo "$line" >> "$dst"
done < "$src"

if [[ "$reached_comment" == false ]]
then
  echo >> "$dst"
  echo "$mob_message" >> "$dst"
fi

cp "$dst" "$src"
rm "$dst"
