#!/usr/bin/env bash

set -e

dir="$(dirname $0)"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
template_file=${GIT_MOB_TEMPLATE=~/.gitmessage.txt}

"$dir/write" "$coauthors_file" "$template_file"
