#!/usr/bin/env bash

set -e

dir="$(dirname "$0")"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
mob_list_file=${GIT_MOB_LIST=~/.git-mob}
template_file=${GIT_MOB_TEMPLATE=~/.gitmessage.txt}

if [[ -z "$1" ]]
then
  "$dir/git-mob-print" "$coauthors_file" "$mob_list_file"
  exit 0
fi

"$dir/write" "$coauthors_file" "$template_file" "$mob_list_file" "$@"
