#!/usr/bin/env bash

set -e

dir="$(dirname "$0")"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
mob_list_file=${GIT_MOB_LIST=~/.git-mob}
template_file=${GIT_MOB_TEMPLATE=~/.gitmessage.txt}

if [[ -z "$1" ]]
then
  "$dir/git-mob-print" "$coauthors_file" "$mob_list_file"
  exit 0
fi

if [[ "$1" == "pick" ]]
then
  export GIT_MOB_COAUTHORS
  cmd="$(cat <<EOF
@dialog@ \
--stdout \
--erase-on-exit \
--default-item 1 \
--checklist \
'Mob up with:' \
$($dir/generate-dialog-args)
EOF
)"
  short_names="$(eval "$cmd")"
else
  short_names="$@"
fi

"$dir/write" "$coauthors_file" "$template_file" "$mob_list_file" "$short_names"
