#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
mob_list_file=${GIT_MOB_LIST=~/.git-mob}
template_file=${GIT_MOB_TEMPLATE=~/.gitmessage.txt}

git-mob-write "$coauthors_file" "$template_file" "$mob_list_file"
