#!/usr/bin/env bash

set -e

dir="$(dirname $0)"
coauthors_file=${GIT_MOB_COAUTHORS=~/.git-coauthors}
template_file=${GIT_MOB_TEMPLATE=~/.gitmessage.txt}

coauthors="$(@jq@ \
  --raw-output \
  --args \
  '.mob = $ARGS.positional' \
  -- \
  $@ \
  < "$coauthors_file"
)"

echo "$coauthors" > "$coauthors_file"
printed="$($dir/git-mob-print)"
echo -e "\n\n$printed" > "$template_file"
echo "$printed"
